### ISSUE TITLE
Can't display STL files by giving file's path

### ISSUE THREAD

**Issue by i-am-neet** [gabotechs/react-stl-viewer#34]
There's a stl file unter `dist/static/sample.stl`

I tried to set the path into `url` as below:

```
class ViewerApp extends Component {

    render(){
        return (
            <div>
                <StlViewer url="dist/static/sample.stl" shadows orbitControls={true} />
            </div>
        );
    }
};

export default ViewerApp;
```

But, got Error messages

```
index.esm.js:24207  Uncaught Error: Could not load dist/static/sample.stl: Invalid typed array length: 16221582540)
    at index.esm.js:24207:1
    at Object.onLoad (index.esm.js:25216:1)
    at three.module.js:41500:1
() @ index.esm.js:24207
() @ index.esm.js:25216
() @ three.module.js:41500
index.esm.js:24207  Uncaught Error: Could not load dist/static/sample.stl: Invalid typed array length: 16221582540)
    at index.esm.js:24207:1
    at Object.onLoad (index.esm.js:25216:1)
    at three.module.js:41500:1
() @ index.esm.js:24207
() @ index.esm.js:25216
() @ three.module.js:41500
index.esm.js:10921  The above error occurred in the <SceneSetup> component:

    at SceneSetup (http://www.localhost:3000/static/js/bundle.js:70447:16)
    at Suspense
    at ErrorBoundary (http://www.localhost:3000/static/js/bundle.js:66760:5)
    at FiberProvider (http://www.localhost:3000/static/js/bundle.js:68836:1)
    at Provider (http://www.localhost:3000/static/js/bundle.js:68502:5)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ index.esm.js:10921
callback @ index.esm.js:10984
callCallback @ index.esm.js:5453
commitUpdateQueue @ index.esm.js:5474
commitLayoutEffectOnFiber @ index.esm.js:16043
commitLayoutMountEffects_complete @ index.esm.js:17456
commitLayoutEffects_begin @ index.esm.js:17442
commitLayoutEffects @ index.esm.js:17380
commitRootImpl @ index.esm.js:20105
commitRoot @ index.esm.js:19971
finishConcurrentRender @ index.esm.js:19151
performConcurrentWorkOnRoot @ index.esm.js:19068
workLoop @ index.esm.js:551
flushWork @ index.esm.js:524
performWorkUntilDeadline @ index.esm.js:818
index.esm.js:24207  Uncaught Error: Could not load dist/static/sample.stl: Invalid typed array length: 16221582540)
    at index.esm.js:24207:1
    at Object.onLoad (index.esm.js:25216:1)
    at three.module.js:41500:1
() @ index.esm.js:24207
() @ index.esm.js:25216
() @ three.module.js:41500
react-dom.development.js:18687  The above error occurred in the <ForwardRef(Canvas)> component:

    at Canvas (http://www.localhost:3000/static/js/bundle.js:68961:5)
    at FiberProvider (http://www.localhost:3000/static/js/bundle.js:68836:1)
    at CanvasWrapper
    at Suspense
    at ErrorBoundary (http://www.localhost:3000/static/js/bundle.js:70583:43)
    at div
    at StlViewer (http://www.localhost:3000/static/js/bundle.js:70608:16)
    at div
    at ViewerApp (http://www.localhost:3000/static/js/bundle.js:844:1)
    at RenderedRoute (http://www.localhost:3000/static/js/bundle.js:41497:5)
    at RenderErrorBoundary (http://www.localhost:3000/static/js/bundle.js:41448:5)
    at Routes (http://www.localhost:3000/static/js/bundle.js:41987:5)
    at Router (http://www.localhost:3000/static/js/bundle.js:41925:15)
    at RouterProvider (http://www.localhost:3000/static/js/bundle.js:41771:5)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:18687
```

Any suggestion?

**Comment by gabotechs** [comment]
It looks like the STL might not be valid. If you download the stl yourself by accessing `http://localhost:3000/dist/static/sample.stl` are you able to retrieve fully and correctly?

One other option that I can think of is if you stl is too big, I see some references in the error message to `Invalid typed array length: 16221582540`. Not completely, as this is managed by three.js, but could that be the size in bytes of the object?

**Comment by i-am-neet** [comment]
> It looks like the STL might not be valid. If you download the stl yourself by accessing `http://localhost:3000/dist/static/sample.stl` are you able to retrieve it fully and correctly?
> 
> One other option that I can think of is if you stl is too big, I see some references in the error message to `Invalid typed array length: 16221582540`. Not completely sure, as this is managed by three.js, but could that be the size in bytes of the object?

Sorry, I found out that I did a silly mistake. Haha...
As you said, the error is because I did't use correct path of stl.
I need to put stl files into `public` folder let my react app can access it.

Thanks for your reply :))
